require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  Exclude:
      - vendor/**/*
      - Gemfile*
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 150
