source 'https://rubygems.org'

gem 'confidential_info_redactor'
gem 'ffi'
gem 'jekyll', '~> 4.3.2'
gem 'nokogumbo', '=2.0.3'

group :jekyll_plugins do
  gem 'html-proofer'
  gem 'jekyll-assets'
  gem 'jekyll_draft'
  gem 'jekyll-environment-variables'
  gem 'jekyll_pre', path: '../'
  gem 'jekyll-sort'
  gem 'jekyll-tagging'
  gem 'kramdown'
end

gem 'debase', '0.2.5.beta2', require: false
gem 'rake', require: false
gem 'ruby-debug-ide', require: false
