source 'https://rubygems.org'

gem 'confidential_info_redactor'
gem 'ffi'
gem 'jekyll', '>= 4.3.2'
gem 'nokogumbo', '=2.0.3'

group :jekyll_plugins do
  gem 'html-proofer'
  gem 'jekyll-assets'
  gem 'jekyll_draft'
  gem 'jekyll-environment-variables'
  gem 'jekyll_pre', path: '../'
  gem 'jekyll-sort'
  gem 'jekyll-tagging'
  gem 'kramdown'
end

group :test, :development do
  gem 'debug', '>= 1.0.0', require: false
  gem 'rake', require: false
  gem 'rspec', require: false
  gem 'rubocop', require: false
  gem 'rubocop-md', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rake', require: false
  gem 'rubocop-rspec', require: false
end
